In [1]:
import yaml
import pandas as pd
from sqlalchemy import create_engine

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [2]:
# Leer credenciales del arhivo YAML
with open("credenciales.yaml", "r") as file:
     config = yaml.safe_load(file)

db = config["mysql"]

# Crear conexión
# Su función es crear un Engine, que es el objeto que SQLAlchemy utiliza para comunicarse con la base de datos.
engine = create_engine(                                     
    f"mysql+pymysql://{db['user']}:{db['password']}@"
    f"{db['host']}:{db['port']}/{db['database']}"
)

2-2 Tipos de Datos

STRING:
	CHAR: Longitud fija 
	VARCHAR: Longitud variables. Hasta 256 caracteres.
	TEXT/BLOB: Grandes longitudes de datos como cartas, mails, reseñas, comentarios.
	
NUMERICO:
	INT: Guardar numeros enteros
	FLOAT/DOUBLE/DECIMAL: Para guardar numeros decimales.

LOGICOS:
	BOOLEANOS:Guardar valores True o False
	
DATE TIME/ TIME STAMP:
	Guardar fechas en formato YYYY-MM-DD hh:mm:ss

TIME:
	Guardar horas en formato hh:mm:ss

DATE:
	Guardar fechas en formato YYYY-MM-DD

In [3]:
# 2-7 Perfilamiento - Histogramas y Frecuencias

# Consulta SQL
query = """
select
       * 
from    
       preparacion.hotel 
limit  10;
"""

# Guardar resultado en DataFrame
df = pd.read_sql(query, engine)
df.head(10)

,Hotel,Cancelado,Tiempo_entre_Reserva_y_Llegada,Ano_Llegada,Mes_Llegada,Semana_de_Llegada,Dia_de_Llegada,Mes,Fecha,Noches_de_Fin_de_Semana,Noches_Entre_Semana,Adultos,Ninos,Bebes,Comida,Codigo_Pais,Pais,Segmento_de_Mercado,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phonenumber,credit_card
0,Hotel del Monte,0,342,2015,July,27,1,7,2015-7-1,0,0,2,0.0,0,Desayuno,PRT,Portugal,Directo,Directo,0,0,0,C,C,3,No Deposit,NaN,None,0,Transient,0.0,0,0,Check-Out,42186,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Hotel del Monte,0,737,2015,July,27,1,7,2015-7-1,0,0,2,0.0,0,Desayuno,PRT,Portugal,Directo,Directo,0,0,0,C,C,4,No Deposit,NaN,None,0,Transient,0.0,0,0,Check-Out,42186,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Hotel del Monte,0,7,2015,July,27,1,7,2015-7-1,0,1,1,0.0,0,Desayuno,GBR,United Kingdom of Great Britain and Northern I...,Directo,Directo,0,0,0,A,C,0,No Deposit,NaN,None,0,Transient,75.0,0,0,Check-Out,42187,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Hotel del Monte,0,13,2015,July,27,1,7,2015-7-1,0,1,1,0.0,0,Desayuno,GBR,United Kingdom of Great Britain and Northern I...,Empresarial,Empresarial,0,0,0,A,A,0,No Deposit,304.0,None,0,Transient,75.0,0,0,Check-Out,42187,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Hotel del Monte,0,14,2015,July,27,1,7,2015-7-1,0,2,2,0.0,0,Desayuno,GBR,United Kingdom of Great Britain and Northern I...,Agencia Viajes Online,TA/TO,0,0,0,A,A,0,No Deposit,240.0,None,0,Transient,98.0,0,1,Check-Out,42188,Linda Hines,LHines@verizon.com,713-226-5883,************5498
5,Hotel del Monte,0,14,2015,July,27,1,7,2015-7-1,0,2,2,0.0,0,Desayuno,GBR,United Kingdom of Great Britain and Northern I...,Agencia Viajes Online,TA/TO,0,0,0,A,A,0,No Deposit,240.0,None,0,Transient,98.0,0,1,Check-Out,42188,Jasmine Fletcher,JFletcher43@xfinity.com,190-271-6743,************9263
6,Hotel del Monte,0,0,2015,July,27,1,7,2015-7-1,0,2,2,0.0,0,Desayuno,PRT,Portugal,Directo,Directo,0,0,0,C,C,0,No Deposit,NaN,None,0,Transient,107.0,0,0,Check-Out,42188,Dylan Rangel,Rangel.Dylan@comcast.net,420-332-5209,************6994
7,Hotel del Monte,0,9,2015,July,27,1,7,2015-7-1,0,2,2,0.0,0,Todo Incluido,PRT,Portugal,Directo,Directo,0,0,0,C,C,0,No Deposit,303.0,None,0,Transient,103.0,0,1,Check-Out,42188,William Velez,Velez_William@mail.com,286-669-4333,************8729
8,Hotel del Monte,1,85,2015,July,27,1,7,2015-7-1,0,3,2,0.0,0,Desayuno,PRT,Portugal,Agencia Viajes Online,TA/TO,0,0,0,A,A,0,No Deposit,240.0,None,0,Transient,82.0,0,1,Canceled,42130,Steven Murphy,Steven.Murphy54@aol.com,341-726-5787,************3639
9,Hotel del Monte,1,75,2015,July,27,1,7,2015-7-1,0,3,2,0.0,0,Desayuno y Cena,PRT,Portugal,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,15.0,None,0,Transient,105.5,0,0,Canceled,42116,Michael Moore,MichaelMoore81@outlook.com,316-648-6176,************9190

In [4]:
# Obtener los valores unicos de la columna hotel

query = """
select 
       distinct(hotel)
from    
       preparacion.hotel;
"""
df = pd.read_sql(query, engine)

df

             hotel
0  Hotel del Monte
1  Hotel de Ciudad

In [5]:
#Obtener los valores unicos de la columna comida

query = """
select 
       distinct(comida)
from
       preparacion.hotel;
"""
df = pd.read_sql(query, engine)

df

            comida
0         Desayuno
1    Todo Incluido
2  Desayuno y Cena
3       Sin Comida
4   No Información

In [6]:
#Contar el número de filas según por el tipo de comida

query = """
select
       comida, 
       count(*)
from 
     preparacion.hotel
group by 1
order by 2 desc;
"""
df = pd.read_sql(query, engine)

df.head(10)

            comida  count(*)
0         Desayuno     92310
1  Desayuno y Cena     14463
2       Sin Comida     10650
3   No Información      1169
4    Todo Incluido       798

In [7]:
#Contar el número de filas segun el pais*/

query = """
select 
       pais,
       count(*)
from
       preparacion.hotel 
group by 1
order by 2 desc;
"""     
df = pd.read_sql(query, engine)

df.head(10)

                                                pais  count(*)
0                                           Portugal     49078
1  United Kingdom of Great Britain and Northern I...     12129
2                                             France     10415
3                                              Spain      8568
4                                            Germany      7287
5                                              Italy      3766
6                                            Ireland      3375
7                                            Belgium      2342
8                                              China      2278
9                                             Brazil      2224

In [8]:
# Conteo de filas segun el tipo de consumidor

query = """
select 	
        customer_type, 
        count(*) as cuenta
from
        preparacion.hotel
group by 1
order by 2 desc;
"""     
df = pd.read_sql(query, engine)

df.head(10)

     customer_type  cuenta
0        Transient   89613
1  Transient-Party   25124
2         Contract    4076
3            Group     577

In [9]:
# Noches entre semana que se queda la gente */

query = """
select
       Noches_Entre_Semana, 
       count(*) as conteo
from
       preparacion.hotel
group by 1
order by 1 asc;
"""     
df = pd.read_sql(query, engine)

df.head(10)

   Noches_Entre_Semana  conteo
0                    0    7645
1                    1   30310
2                    2   33684
3                    3   22258
4                    4    9563
5                    5   11077
6                    6    1499
7                    7    1029
8                    8     656
9                    9     231

In [10]:
# Numero de visitantes adultos agrupado por nombre del pais

query = """
select
       pais, 
       sum(adultos) as visitas
from
       preparacion.hotel
group by 1
order by 2 desc;
"""     
df = pd.read_sql(query, engine)
df.head(10)

                                                pais  visitas
0                                           Portugal  86799.0
1  United Kingdom of Great Britain and Northern I...  23223.0
2                                             France  20291.0
3                                              Spain  16615.0
4                                            Germany  13703.0
5                                              Italy   7384.0
6                                            Ireland   6570.0
7                                            Belgium   4588.0
8                                             Brazil   4450.0
9                                              China   4394.0

In [11]:
# Cuantos paises mandaron 1 adulto, cuandos 2 adultos, etc.

query = """
select 	
       visitas, 
       count(*) as Numero_de_paises
from   
       (
       select	
              pais, 
              sum(adultos) as visitas
       from
              preparacion.hotel
       group by 1
       order by 2
       ) as A
group by visitas
order by visitas asc;
"""     
df = pd.read_sql(query, engine)
df.head(10)

   visitas  Numero_de_paises
0      1.0                 2
1      2.0                29
2      3.0                 4
3      4.0                10
4      5.0                 4
5      6.0                 6
6      7.0                 3
7      8.0                 6
8      9.0                 2
9     10.0                 2

In [12]:
# 2-8 Binning */

# Conteo de filas agrupado por noches_entre_semana y adr */

query = """
select 
       noches_entre_semana,
       adr,
       count(*)
from   
       preparacion.hotel
group by 1,2
order by 1,2;
"""     
df = pd.read_sql(query, engine)
df.head(10)

   noches_entre_semana   adr  count(*)
0                    0   0.0       838
1                    0   1.0         1
2                    0   3.0         1
3                    0   4.0         2
4                    0   5.0         1
5                    0   6.0        15
6                    0   6.5         1
7                    0   8.0         5
8                    0   9.0         1
9                    0  12.0        15

In [13]:
# Generar buckets para noches_entre_semana

query = """
select 
       case
            when noches_entre_semana <= 5 then "hasta_5_noches"
            when noches_entre_semana > 5 and noches_entre_semana <= 15 then "hasta_15_noches"
            else "Mas_de_15_noches"
       end as cantidad_bin,
       adr,
       count(*) as reservaciones
from
       preparacion.hotel
group by 1,2
order by 1,2;
"""     
df = pd.read_sql(query, engine)
df.head(10)

      cantidad_bin   adr  reservaciones
0  hasta_15_noches -6.38              1
1  hasta_15_noches  0.00             36
2  hasta_15_noches  0.50              1
3  hasta_15_noches  1.56              1
4  hasta_15_noches  1.80              1
5  hasta_15_noches  2.00              1
6  hasta_15_noches  3.38              1
7  hasta_15_noches  4.00              1
8  hasta_15_noches  5.25              1
9  hasta_15_noches  6.40              1

In [14]:
#Generar buckets para noches_entre_semana y adr

query = """
select
       case
            when noches_entre_semana <= 5 then "Hasta_5_noches"
            when noches_entre_semana <= 15 then "Hasta_15_noches"
            else "Mas_de_15_noches"
       end as cantidad_noches,
       case
            when adr <= 100 then "Hasta_100_dolares_la_noche"
            when adr <= 250 then "Hasta_250_dolares_la_noche"
            else "Mas_de_250_dolares_la_noche"
       end as categoria_adr,
       count(*) as conteo
from
       preparacion.hotel
group by 1,2
order by 1,2; 
"""     
df = pd.read_sql(query, engine)
df.head(10)

    cantidad_noches                categoria_adr  conteo
0   Hasta_15_noches   Hasta_100_dolares_la_noche    2603
1   Hasta_15_noches   Hasta_250_dolares_la_noche    2022
2   Hasta_15_noches  Mas_de_250_dolares_la_noche      71
3    Hasta_5_noches   Hasta_100_dolares_la_noche   64897
4    Hasta_5_noches   Hasta_250_dolares_la_noche   48467
5    Hasta_5_noches  Mas_de_250_dolares_la_noche    1173
6  Mas_de_15_noches   Hasta_100_dolares_la_noche     138
7  Mas_de_15_noches   Hasta_250_dolares_la_noche      19

In [16]:
# Función Round
# Permite hacer redondeos a milesimas, centesimas, y si el argmento es negativo puede hacer el redondeo a decenas, centenas, miles, etc
# Por ejemplo round(n,-1) haran el redondeo de n a la decena más cercana
# Decenas:  0-4  baja a la decena  inmediata anterior, 5-9   sube a la siguiente decena
# Centenas: 0-49 baja a la centena inmediata anterior, 50-99 sube a la siguiente centena
# Miles:    0-499 baja al mil inmediato anterior     , 500-999 sube al siguiente mil
query = """
select
       distinct Tiempo_entre_Reserva_y_Llegada,
       round(Tiempo_entre_Reserva_y_Llegada,-1) as Redondeo_a_decenas
from
       preparacion.hotel
order by 2 asc;
"""
df = pd.read_sql(query, engine)
df.head(10)

   Tiempo_entre_Reserva_y_Llegada  Redondeo_a_decenas
0                               0                   0
1                               1                   0
2                               2                   0
3                               3                   0
4                               4                   0
5                               5                  10
6                               6                  10
7                               7                  10
8                               8                  10
9                               9                  10

In [17]:
# Redondeo a centenas
query="""
select
       distinct Tiempo_entre_Reserva_y_Llegada,
       round(Tiempo_entre_Reserva_y_Llegada,-2) as Redondeo_a_centenas
from
       preparacion.hotel
order by 2 asc;
"""
df = pd.read_sql(query, engine)
df.tail(10)

     Tiempo_entre_Reserva_y_Llegada  Redondeo_a_centenas
469                             594                  600
470                             601                  600
471                             605                  600
472                             608                  600
473                             615                  600
474                             622                  600
475                             626                  600
476                             629                  600
477                             709                  700
478                             737                  700

In [18]:
# Creación de bins usando redondeo a centenas

query="""
select
       round(tiempo_entre_reserva_y_llegada,-2) as tiempo_redondeado_centenas,
       count(*) as conteo_filas
from
       preparacion.hotel
group by 1
order by 1 asc;
"""
df = pd.read_sql(query, engine)
df.head(20)

   tiempo_redondeado_centenas  conteo_filas
0                           0         50281
1                         100         36234
2                         200         19203
3                         300          9748
4                         400          2807
5                         500           851
6                         600           264
7                         700             2

In [19]:
# FUNCIONES DE VENTANA - OVER - PARTITION BY
# Las funciones de ventana (window functions) en SQL son funciones que permiten hacer cálculos sobre un conjunto de filas relacionadas con la fila actual, sin convertir esas filas en una sola fila.
# Permite usar funciones de agregacion sin tener que mostrar la tabla de resultados agrupada
# Permite aplicar una funcion de agregacion a un bloque de filas y que ese resultado aparezca para todas las filas de la tabla

# Total de clientes tipo "adulto"

query="""
select
       sum(adultos)
from   
       preparacion.hotel
"""
df = pd.read_sql(query, engine)
df.head(10)

   sum(adultos)
0      221636.0

In [22]:
# Mostrar el Total de clientes de tipo "adulto" en una nueva columna sin usar group by*/

query="""
select 
       hotel, 
       cancelado, 
       sum(adultos) over () as suma_total
from   
       preparacion.hotel;
"""
df = pd.read_sql(query, engine)
df.head(10)

             hotel  cancelado  suma_total
0  Hotel del Monte          0    221636.0
1  Hotel del Monte          0    221636.0
2  Hotel del Monte          0    221636.0
3  Hotel del Monte          0    221636.0
4  Hotel del Monte          0    221636.0
5  Hotel del Monte          0    221636.0
6  Hotel del Monte          0    221636.0
7  Hotel del Monte          0    221636.0
8  Hotel del Monte          1    221636.0
9  Hotel del Monte          1    221636.0

In [23]:
# Total de clientes adultos por tipo de hotel 

query="""
select 
    hotel,
    sum(adultos)
from
    preparacion.hotel
group by hotel
"""
df = pd.read_sql(query, engine)
df.head(10)

             hotel  sum(adultos)
0  Hotel del Monte       74798.0
1  Hotel de Ciudad      146838.0

In [29]:
# Mostrar el Total de clientes adultos agrupando por tipo de hotel

query="""
select
    hotel,
    cancelado,
    sum(adultos) over (partition by hotel) as suma_parcial
from
    preparacion.hotel;
"""
df = pd.read_sql(query, engine)
df.head(10)

             hotel  cancelado  suma_parcial
0  Hotel de Ciudad          0      146838.0
1  Hotel de Ciudad          0      146838.0
2  Hotel de Ciudad          0      146838.0
3  Hotel de Ciudad          0      146838.0
4  Hotel de Ciudad          0      146838.0
5  Hotel de Ciudad          0      146838.0
6  Hotel de Ciudad          0      146838.0
7  Hotel de Ciudad          0      146838.0
8  Hotel de Ciudad          0      146838.0
9  Hotel de Ciudad          0      146838.0

In [27]:
df.tail(10)

                  hotel  cancelado  suma_parcial
119380  Hotel del Monte          0       74798.0
119381  Hotel del Monte          0       74798.0
119382  Hotel del Monte          0       74798.0
119383  Hotel del Monte          0       74798.0
119384  Hotel del Monte          0       74798.0
119385  Hotel del Monte          0       74798.0
119386  Hotel del Monte          0       74798.0
119387  Hotel del Monte          0       74798.0
119388  Hotel del Monte          0       74798.0
119389  Hotel del Monte          0       74798.0

In [ ]:
# 2-9 Cuantiles

# Función ntile

# Nota: La funcion cuantil Qx(p) de una funcion de probabilidad acumulada Fx(x) se define como el valor mas pequeño de x tal que Fx(x)=p  
# Es decir, Qx(p)=min{xER | Fx(x) = p }
# https://statproofbook.github.io/P/duni-qf.html

# La función ntile no realiza la misma tarea, sino que divide las filas de una partición ordenada en un numero n de grupos, 
# y para cada fila asigna el grupo al que pertence.
# https://www.mysqltutorial.org/mysql-window-functions/mysql-ntile-function/

In [51]:
# Hacer una partición de 10 grupos de las filas de la tabla, usando la columna "noches_entre_semana" ordenadas por "noches entre semana"

query="""
select
    pais,
    noches_entre_semana,
    ntile(10) over (order by noches_entre_semana) as ntile_10
from
    preparacion.hotel
order by 3 asc;
"""
df = pd.read_sql(query, engine)
df.head(10)

,pais,noches_entre_semana,ntile_10
0,United Kingdom of Great Britain and Northern I...,1,1
1,Portugal,1,1
2,Portugal,1,1
3,Portugal,1,1
4,Portugal,1,1
5,Portugal,1,1
6,Portugal,1,1
7,France,1,1
8,Portugal,1,1
9,Portugal,1,1

In [52]:
df.tail(10)

            pais  noches_entre_semana  ntile_10
119380   Austria                    6        10
119381  Portugal                    6        10
119382   Belgium                    6        10
119383    Brazil                    6        10
119384    France                    6        10
119385  Portugal                    6        10
119386    France                    6        10
119387  Portugal                    6        10
119388  Portugal                    6        10
119389   Belgium                    6        10

In [54]:
# Obtener el decil, valor minimo, valor maximo y conteo de filas sobre cada decil del numero de noches_entre_semana.

query="""
select
    decil,
    min(noches_entre_semana),
    max(noches_entre_semana),
    count(*)
from
    (
    select
        pais,
        noches_entre_semana,
        ntile(10) over (order by noches_entre_semana) as decil
    from preparacion.hotel
    order by noches_entre_semana
    ) as T1
group by decil;
"""
df = pd.read_sql(query, engine)
df.head(10)

   decil  min(noches_entre_semana)  max(noches_entre_semana)  count(*)
0      1                         0                         1     11939
1      3                         1                         1     11939
2      2                         1                         1     11939
3      4                         1                         2     11939
4      6                         2                         2     11939
5      5                         2                         2     11939
6      7                         2                         3     11939
7      8                         3                         4     11939
8      9                         4                         5     11939
9     10                         5                        50     11939

In [ ]:
# Función PERCENT_RANK */
# Percent_rank(): Returns the percentage of partition values less than the value in the current row, excluding the highest value. 
# Return values range from 0 to 1 and represent the row relative rank, calculated as the result of this formula, 
# where rank is the row rank and rows is the number of partition rows:
# https://dev.mysql.com/doc/refman/8.4/en/window-function-descriptions.html#function_percent-rank

In [58]:
# Obtener el percentil de la fila noches_entre_semana ordenando por noches_entre_semana */
# La columna "percentil" muestra el porcentaje de filas de la tabla tales que su columna "noches_entre_semana" es <= al valor de "noches_entre_semana" de la fila actual */

query="""
select
    pais,
    noches_entre_semana,
    percent_rank() over (order by noches_entre_semana) as percentil
from
    preparacion.hotel
order by noches_entre_semana;
"""
df = pd.read_sql(query, engine)
df.head(10)

       pais  noches_entre_semana  percentil
0  Portugal                    0        0.0
1  Portugal                    0        0.0
2  Portugal                    0        0.0
3  Portugal                    0        0.0
4  Portugal                    0        0.0
5  Portugal                    0        0.0
6  Portugal                    0        0.0
7    Brazil                    0        0.0
8    France                    0        0.0
9    France                    0        0.0

In [59]:
df.tail(10)

,pais,noches_entre_semana,percentil
119380,United States of America (the),30,0.999891
119381,United Kingdom of Great Britain and Northern I...,32,0.999933
119382,Spain,33,0.999941
119383,Portugal,34,0.999950
119384,Portugal,35,0.999958
119385,United Kingdom of Great Britain and Northern I...,40,0.999966
119386,Portugal,40,0.999966
119387,United Kingdom of Great Britain and Northern I...,41,0.999983
119388,Portugal,42,0.999992
119389,Portugal,50,1.000000

In [66]:
# Los valores unicos de noches_entre_semana y percentil
# se interpretan de la siguiente manera:
# El 0 % de los datos es <= 0
# El 6.403437502617494 % de los datos es <= 1
# El 31.79103602509444 % de los datos es <= 2
#	...
# El 99.99916240189632 % de los datos es <= 42
# El 100% de los datos es <= 50

query="""
select
    distinct noches_entre_semana, percentil*100 as percentil
from
    (
    select
        pais, 
        noches_entre_semana, 
        percent_rank() over (order by noches_entre_semana) as percentil
    from
        preparacion.hotel
    order by noches_entre_semana
    ) as T;
"""
df = pd.read_sql(query, engine)
df.head(50)

    noches_entre_semana   percentil
0                     0    0.000000
1                     1    6.403438
2                     2   31.791036
3                     3   60.004691
4                     4   78.647949
5                     5   86.657900
6                     6   95.935974
7                     7   97.191534
8                     8   98.053422
9                     9   98.602886
10                   10   98.796372
11                   11   99.664123
12                   12   99.711029
13                   13   99.746208
14                   14   99.768823
15                   15   99.798139
16                   16   99.869335
17                   17   99.882736
18                   18   99.886087
19                   19   99.891112
20                   20   99.927967
21                   21   99.962308
22                   22   99.974872
23                   24   99.980735
24                   25   99.983248
25                   26   99.988274
26                   30   99.989111
27                   32   99.993299
28                   33   99.994137
29                   34   99.994974
30                   35   99.995812
31                   40   99.996650
32                   41   99.998325
33                   42   99.999162
34                   50  100.000000

In [71]:
# Obtener el minimo, maximo y recuento para cada percentil */

query="""
select
    round(percentil,3), 
    min(noches_entre_semana), 
    max(noches_entre_semana), 
    count(*)
from
    (
    select 
        pais, 
        noches_entre_semana, 
        percent_rank() over (order by noches_entre_semana) as percentil
    from 
        preparacion.hotel
    order by noches_entre_semana
    ) as T
group by 1;
"""
df = pd.read_sql(query, engine)
df.head(50)

,"round(percentil,3)",min(noches_entre_semana),max(noches_entre_semana),count(*)
0,0.000,0,0,7645
1,0.064,1,1,30310
2,0.318,2,2,33684
3,0.600,3,3,22258
4,0.786,4,4,9563
5,0.867,5,5,11077
6,0.959,6,6,1499
7,0.972,7,7,1029
8,0.981,8,8,656
9,0.986,9,9,231
10,0.988,10,10,1036
11,0.997,11,13,125
12,0.998,14,15,120
13,0.999,16,20,111
14,1.000,21,50,46

In [72]:
# 2-10 Limpieza de Datos

# Tabla generos
select * 
from preparacion.generos;
/*
ID_Cliente	Genero
1		Femenino
2		Femenina
3		F
4		F
5		F
6		F
7		Femenino
8		Femenino
9		Femenina
10		Femenina
*/

SyntaxError: invalid syntax (1225003914.py, line 4)